/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-$4DEVAL(Replace string:C233($1.PRODUCT_NAME;" ";"-")).h
 #	source generated by 4D Plugin Wizard
 #	Project : $4DEVAL($1.PRODUCT_NAME)
 #	author : $4DEVAL($1.AUTHOR)
 #	$4DEVAL($1.CREATE_DATE)
 #  <!--#4DEVAL $1.FILENAME:=Replace string:C233(Replace string:C233(Uppercase:C13("PLUGIN "+$1.PRODUCT_NAME);" ";"_");"-";"_")-->
 # --------------------------------------------------------------------------------*/

#ifndef $4DEVAL($1.FILENAME)_H
#define $4DEVAL($1.FILENAME)_H

#include "4DPluginAPI.h"

#pragma mark -
<!--#4DCODE
    $path:=Path to object:C1547(Get 4D folder:C485(Database folder:K5:14))
    $manifestJsonPath:=$path.parentFolder+"manifest.json"
    $manifestJson:=Document to text:C1236($manifestJsonPath;"utf-8")
    $manifest:=JSON Parse:C1218($manifestJson)
    ARRAY OBJECT:C1221($commands;0)
    OB GET ARRAY:C1229($manifest;"commands";$commands)
    C_OBJECT:C1216($command)
    ARRAY LONGINT:C221($pos;0)
    ARRAY LONGINT:C221($len;0)
--><!--#4DLOOP $commands-->$4DEVAL($command:=$commands{$commands})<!--#4DIF (Match regex:C1019("([^\\u0028]+)";$command.syntax;1;$pos;$len))-->$4DEVAL($commandSyntax:=Substring:C12($command.syntax;$pos{1};$len{1}))
void $4DEVAL(Replace string:C233($commandSyntax;" ";"_"))(PA_PluginParameters params);<!--#4DENDIF--><!--#4DENDLOOP-->

#endif /* $4DEVAL($1.FILENAME)_H */
